warning1: You are on your first warning, any further offenses will result in harsher punishments.
warning2: You have been kicked for breaking a rule, any further offenses will result in harsher punishments
warning3: you were banned for 1 hour. Please make an appeal on the forums for an unban.
warning4: you were banned for 2 hours. Please make an appeal on the forums for an unban.
warning5: you were banned for 4 hours. Please make an appeal on the forums for an unban
warning6: you were banned for 10 hours please make an appeal on the forums for an unban.
warning7: you were banned for 24 hours. Please make an appeal on the forums for an unban 
warning8: You were banned for good of the community.